<?php
/**
 * Title: Jobs - Banner with image(right) and text
 * Slug: jobs/banner-right
 * Categories: call-to-action
 * Viewport Width: 1280
 */
?>

<!-- wp:blockstrap/blockstrap-widget-container {"mb_lg":"","content":"\u003cdiv class=\u0022bs-counter-number-wrapper text-dark text-start fw-bold  h1 \u0022  \u003e\u003cspan class=\u0022bs-counter-number\u0022 data-auicounter data-auistart=\u00220\u0022 data-auiend=\u002256\u0022 data-auiduration=\u00222000\u0022 data-auisep=\u0022\u0022\u003e56\u003c/span\u003e\u003cspan class=\u0022bs-counter-suffix\u0022\u003eK+\u003c/span\u003e\u003c/div\u003e\u003cdiv class=\u0022bs-counter-title text-start fs-5 \u0022 \u003eMonthly Users\u003c/div\u003e"} -->
[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","mb_lg":"","pt":"3","pt_lg":"6","pb_lg":"5","flex_align_items_lg":"align-items-lg-center"} -->
[bs_container container='row'  h100=''  row_cols='1'  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='3'  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='6'  pr_lg=''  pb_lg='5'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-3 pt-lg-6 pb-5 row-cols-1 row align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_lg":"7","mb_lg":"","pl":"3","pr_lg":"7"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg='7'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl='3'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='7'  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined ps-3 pe-7 col-7 col"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Land a job that you'll love going to every day.","html_tag":"h2","text_color_custom":"#0c0d24","font_size":"h1","font_weight":"font-weight-bold"} -->
<h2 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 font-weight-bold h1">Land a job that you'll love going to every day.</h2>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Search for jobs, read employee reviews, and compare salaries with our powerful tools.","html_tag":"p","text_color_custom":"#0c0d24","font_size":"fs-5","mb_lg":"4","pb_lg":"2"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-4 pb-2 fs-5">Search for jobs, read employee reviews, and compare salaries with our powerful tools.</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-icon-box {"icon_class":"fa-solid fa-check","title":"Tap into a global talent pool.","title_tag":"h4","type":"none","icon_position":"left","icon_type":"iconbox","iconbox_size":"extrasmall","icon_color":"primary","icon_text_align_lg":"text-lg-left","title_size":"h5","mb_lg":"3","ml_lg":"4","content":"\u003cdiv class=\u0022blockstrap-iconbox position-relative h-100 mb-3 ms-4 d-flex align-items-center \u0022  \u003e\u003cdiv class=\u0022blockstrap-iconbox-icon  me-3 me-3 text-primary text-start \u0022  \u003e\u003ci class=\u0022fa-solid fa-check   iconbox rounded-circle iconextrasmall \u0022\u003e\u003c/i\u003e\u003c/div\u003e\u003cdiv class=\u0022iconbox-text-wrap  \u0022\u003e\u003ch4 class=\u0022blockstrap-iconbox-title text-center h5   mb-0\u0022  \u003eTap into a global talent pool.\u003c/h4\u003e\u003c/div\u003e\u003c/div\u003e"} -->
[bs_iconbox icon_class='fa-solid fa-check'  title='Tap into a global talent pool.'  title_tag='h4'  description=''  type='none'  page_id=''  post_id=''  custom_url=''  icon_position='left'  icon_type='iconbox'  iconbox_size='extrasmall'  icon_size='h3'  icon_size_custom=''  icon_color='primary'  icon_color_custom=''  icon_bg='primary'  icon_text_align=''  icon_text_align_md=''  icon_text_align_lg='text-lg-left'  icon_pb=''  title_size='h5'  title_size_custom=''  title_font_line_height=''  title_color=''  title_color_custom=''  title_font_weight=''  title_font_case=''  title_text_justify='false'  title_text_align=''  title_text_align_md=''  title_text_align_lg='text-lg-center'  title_pb=''  desc_size=''  desc_size_custom=''  desc_font_line_height=''  desc_color=''  desc_color_custom=''  desc_font_weight=''  desc_font_case=''  desc_text_justify='false'  desc_text_align=''  desc_text_align_md=''  desc_text_align_lg='text-lg-center'  desc_pb=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg='4'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  hover_animations=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-icon-box -->

<!-- wp:blockstrap/blockstrap-widget-icon-box {"icon_class":"fa-solid fa-check","title":"Pay only for the candidates you reach out to","title_tag":"h4","type":"none","icon_position":"left","icon_type":"iconbox","iconbox_size":"extrasmall","icon_color":"primary","icon_text_align_lg":"text-lg-left","title_size":"h5","mb_lg":"3","ml_lg":"4","content":"\u003cdiv class=\u0022blockstrap-iconbox position-relative h-100 mb-3 ms-4 d-flex align-items-center \u0022  \u003e\u003cdiv class=\u0022blockstrap-iconbox-icon  me-3 me-3 text-primary text-start \u0022  \u003e\u003ci class=\u0022fa-solid fa-check   iconbox rounded-circle iconextrasmall \u0022\u003e\u003c/i\u003e\u003c/div\u003e\u003cdiv class=\u0022iconbox-text-wrap  \u0022\u003e\u003ch4 class=\u0022blockstrap-iconbox-title text-center h5   mb-0\u0022  \u003ePay only for the candidates you reach out to\u003c/h4\u003e\u003c/div\u003e\u003c/div\u003e"} -->
[bs_iconbox icon_class='fa-solid fa-check'  title='Pay only for the candidates you reach out to'  title_tag='h4'  description=''  type='none'  page_id=''  post_id=''  custom_url=''  icon_position='left'  icon_type='iconbox'  iconbox_size='extrasmall'  icon_size='h3'  icon_size_custom=''  icon_color='primary'  icon_color_custom=''  icon_bg='primary'  icon_text_align=''  icon_text_align_md=''  icon_text_align_lg='text-lg-left'  icon_pb=''  title_size='h5'  title_size_custom=''  title_font_line_height=''  title_color=''  title_color_custom=''  title_font_weight=''  title_font_case=''  title_text_justify='false'  title_text_align=''  title_text_align_md=''  title_text_align_lg='text-lg-center'  title_pb=''  desc_size=''  desc_size_custom=''  desc_font_line_height=''  desc_color=''  desc_color_custom=''  desc_font_weight=''  desc_font_case=''  desc_text_justify='false'  desc_text_align=''  desc_text_align_md=''  desc_text_align_lg='text-lg-center'  desc_pb=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg='4'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  hover_animations=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-icon-box -->

<!-- wp:blockstrap/blockstrap-widget-icon-box {"icon_class":"fa-solid fa-check","title":"Save time and money by posting jobs for free.","title_tag":"h4","type":"none","icon_position":"left","icon_type":"iconbox","iconbox_size":"extrasmall","icon_color":"primary","icon_text_align_lg":"text-lg-left","title_size":"h5","mb_lg":"3","ml_lg":"4","content":"\u003cdiv class=\u0022blockstrap-iconbox position-relative h-100 mb-3 ms-4 d-flex align-items-center \u0022  \u003e\u003cdiv class=\u0022blockstrap-iconbox-icon  me-3 me-3 text-primary text-start \u0022  \u003e\u003ci class=\u0022fa-solid fa-check   iconbox rounded-circle iconextrasmall \u0022\u003e\u003c/i\u003e\u003c/div\u003e\u003cdiv class=\u0022iconbox-text-wrap  \u0022\u003e\u003ch4 class=\u0022blockstrap-iconbox-title text-center h5   mb-0\u0022  \u003eSave time and money by posting jobs for free.\u003c/h4\u003e\u003c/div\u003e\u003c/div\u003e"} -->
[bs_iconbox icon_class='fa-solid fa-check'  title='Save time and money by posting jobs for free.'  title_tag='h4'  description=''  type='none'  page_id=''  post_id=''  custom_url=''  icon_position='left'  icon_type='iconbox'  iconbox_size='extrasmall'  icon_size='h3'  icon_size_custom=''  icon_color='primary'  icon_color_custom=''  icon_bg='primary'  icon_text_align=''  icon_text_align_md=''  icon_text_align_lg='text-lg-left'  icon_pb=''  title_size='h5'  title_size_custom=''  title_font_line_height=''  title_color=''  title_color_custom=''  title_font_weight=''  title_font_case=''  title_text_justify='false'  title_text_align=''  title_text_align_md=''  title_text_align_lg='text-lg-center'  title_pb=''  desc_size=''  desc_size_custom=''  desc_font_line_height=''  desc_color=''  desc_color_custom=''  desc_font_weight=''  desc_font_case=''  desc_text_justify='false'  desc_text_align=''  desc_text_align_md=''  desc_text_align_lg='text-lg-center'  desc_pb=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg='4'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  hover_animations=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-icon-box -->

<!-- wp:blockstrap/blockstrap-widget-icon-box {"icon_class":"fa-solid fa-check","title":"Hiring solutions that adapt to your seasonal needs.","title_tag":"h4","type":"none","icon_position":"left","icon_type":"iconbox","iconbox_size":"extrasmall","icon_color":"primary","icon_text_align_lg":"text-lg-left","title_size":"h5","mb_lg":"3","ml_lg":"4","content":"\u003cdiv class=\u0022blockstrap-iconbox position-relative h-100 mb-3 ms-4 d-flex align-items-center \u0022  \u003e\u003cdiv class=\u0022blockstrap-iconbox-icon  me-3 me-3 text-primary text-start \u0022  \u003e\u003ci class=\u0022fa-solid fa-check   iconbox rounded-circle iconextrasmall \u0022\u003e\u003c/i\u003e\u003c/div\u003e\u003cdiv class=\u0022iconbox-text-wrap  \u0022\u003e\u003ch4 class=\u0022blockstrap-iconbox-title text-center h5   mb-0\u0022  \u003eHiring solutions that adapt to your seasonal needs.\u003c/h4\u003e\u003c/div\u003e\u003c/div\u003e"} -->
[bs_iconbox icon_class='fa-solid fa-check'  title='Hiring solutions that adapt to your seasonal needs.'  title_tag='h4'  description=''  type='none'  page_id=''  post_id=''  custom_url=''  icon_position='left'  icon_type='iconbox'  iconbox_size='extrasmall'  icon_size='h3'  icon_size_custom=''  icon_color='primary'  icon_color_custom=''  icon_bg='primary'  icon_text_align=''  icon_text_align_md=''  icon_text_align_lg='text-lg-left'  icon_pb=''  title_size='h5'  title_size_custom=''  title_font_line_height=''  title_color=''  title_color_custom=''  title_font_weight=''  title_font_case=''  title_text_justify='false'  title_text_align=''  title_text_align_md=''  title_text_align_lg='text-lg-center'  title_pb=''  desc_size=''  desc_size_custom=''  desc_font_line_height=''  desc_color=''  desc_color_custom=''  desc_font_weight=''  desc_font_case=''  desc_text_justify='false'  desc_text_align=''  desc_text_align_md=''  desc_text_align_lg='text-lg-center'  desc_pb=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg='4'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  hover_animations=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-icon-box -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","row_cols_md":"2","row_cols_lg":"1","mb_lg":""} -->
[bs_container container='row'  h100=''  row_cols='1'  row_cols_md='2'  row_cols_lg='1'  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined row-cols-1 row-cols-md-2 row-cols-lg-1 row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb":"4","mb_lg":""} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb='4'  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mb-4 col"><!-- wp:blockstrap/blockstrap-widget-button {"type":"custom","custom_url":"#","text":"Post a job","link_size":"large","bg_hover":"secondary","font_weight":"font-weight-bold","mt_lg":"4","pt_lg":"3","pb_lg":"3","styleid":"block-uceu972akzk","content":"\u003ca   class=\u0022btn btn-primary btn-lg mt-4 pt-3 pb-3 fw-bold  block-uceu972akzk \u0022\u003ePost a job\u003c/a\u003e \u003cstyle\u003ehtml .editor-styles-wrapper .block-uceu972akzk:hover {background: var(\u002d\u002dwp\u002d\u002dpreset\u002d\u002dcolor\u002d\u002dsecondary) !important;} html .editor-styles-wrapper .block-uceu972akzk.btn:hover {border-color: var(\u002d\u002dwp\u002d\u002dpreset\u002d\u002dcolor\u002d\u002dsecondary) !important;} \u003c/style\u003e"} -->
[bs_button type='custom'  page_id=''  meta_key=''  post_id=''  custom_url='#'  text='Post a job'  icon_class=''  icon_position=''  link_type='btn'  link_size='large'  link_bg='primary'  link_bg_color='#0073aa'  link_bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color=''  text_color_custom=''  bg_hover='secondary'  bg_hover_color='#0073aa'  bg_hover_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color_hover=''  text_color_hover_custom=''  font_size_custom=''  font_weight='font-weight-bold'  font_case=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='4'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg=''  pb_lg='3'  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  display=''  display_md=''  display_lg=''  visibility_conditions=''  css_class=''  styleid='block-uceu972akzk' ]
<!-- /wp:blockstrap/blockstrap-widget-button --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_lg":"5","mb_lg":""} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg='5'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined col-5 col"><!-- wp:blockstrap/blockstrap-widget-image {"img_src":"url","img_url":"<?php echo esc_url( get_theme_file_uri( 'assets/images/demo/innovation.svg' ) ); ?>","fallback_img_src":"default","img_cover":"n","img_rounded":"rounded","mb_lg":"","content":"\u003cfigure class=\u0022  embed-has-actionoverflow-hidden mb-3 \u0022 style=\u0022 \u0022\u003e\u003cimg src=\u0022<?php echo esc_url( get_theme_file_uri( 'assets/images/demo/innovation.svg' ) ); ?>\u0022 class=\u0022mw-100 w-100 rounded embed-item-contain  \u0022   /\u003e\u003c/figure\u003e"} -->
[bs_image img_src='url'  img_image=''  img_image_id=''  img_size=''  img_url='<?php echo esc_url( get_theme_file_uri( 'assets/images/demo/innovation.svg' ) ); ?>'  fallback_img_src='default'  fallback_img_image=''  fallback_img_image_id=''  img_alt=''  img_lazyload=''  img_link_to=''  img_link=''  img_link_lightbox=''  lightbox_size='full'  img_link_hover_effect=''  text=''  col=''  col_md=''  col_lg=''  img_aspect=''  img_cover='n'  img_border=''  img_rounded='rounded'  img_rounded_size=''  img_shadow=''  img_overlay=''  text_color=''  font_size=''  font_size_custom=''  font_weight=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  float=''  float_md=''  float_lg=''  img_mask=''  img_mask_position='center center'  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-image --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->