<?php
/**
 * Title: Jobs: Contact Page
 * Slug: job-board/contact-page
 * Block Types: core/post-content
 * Categories: blockstrap-page-content
 * Viewport Width: 1280
 */
?>

<!-- wp:blockstrap/blockstrap-widget-container {"bg":"light","text_align_lg":"text-lg-center","mb_lg":"","rounded":"rounded","display_lg":"d-lg-none","flex_align_items_lg":"align-items-lg-center"} -->
[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='light'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-none'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined bg-light text-center d-none container rounded align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","row_cols_md":"3","mb_lg":""} -->
[bs_container container='row'  h100=''  row_cols='1'  row_cols_md='3'  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined row-cols-1 row-cols-md-3 row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","text_align_lg":"text-lg-start","mb_lg":"","pt_lg":"5","pr_lg":"4","pb_lg":"5","pl_lg":"4"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-start'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='4'  pb_lg='5'  pl_lg='4'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-5 pe-4 pb-5 ps-4 text-start col"></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","text_align_lg":"text-lg-start","mb_lg":"","pt_lg":"5","pr_lg":"4","pb_lg":"5","pl_lg":"4"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-start'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='4'  pb_lg='5'  pl_lg='4'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-5 pe-4 pb-5 ps-4 text-start col"></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","text_align_lg":"text-lg-start","mb_lg":"","pt_lg":"5","pr_lg":"4","pb_lg":"5","pl_lg":"4"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-start'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='4'  pb_lg='5'  pl_lg='4'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-5 pe-4 pb-5 ps-4 text-start col"></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"text_align_lg":"text-lg-center","mt_lg":"6","mb_lg":"","rounded":"rounded","flex_align_items_lg":"align-items-lg-center"} -->
[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='6'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mt-6 text-center container rounded align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","row_cols_md":"2","mb_lg":"","display_lg":"d-lg-flex","flex_align_items_lg":"align-items-lg-center"} -->
[bs_container container='row'  h100=''  row_cols='1'  row_cols_md='2'  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined row-cols-1 row-cols-md-2 d-flex row align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","bg":"custom-color","bg_color":"#f7f7f7","text_align_lg":"text-lg-start","mb_lg":"","pt_lg":"5","pr_lg":"5","pb_lg":"5","pl_lg":"5","rounded":"rounded"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-color'  bg_color='#f7f7f7'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-start'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='5'  pb_lg='5'  pl_lg='5'  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-5 pe-5 pb-5 ps-5 bg-custom-color text-start col rounded" style="background-color:#f7f7f7"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Here to help","html_tag":"h3","text_color":"dark","font_weight":"font-weight-bold","mb_lg":""} -->
<h3 class="wp-block-blockstrap-blockstrap-widget-heading text-dark font-weight-bold">Here to help</h3>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Have a question about the our service? We're here to help, contact us today!.","html_tag":"div","font_size":"custom","font_size_custom":1,"mb_lg":"4"} -->
<div class="wp-block-blockstrap-blockstrap-widget-heading mb-4" style="font-size:1rem">Have a question about the our service? We're here to help, contact us today!.</div>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:shortcode -->
[contact-form-7 id="1970" title="Contact form 1"]
<!-- /wp:shortcode --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","text_align_lg":"text-lg-center","mb_lg":"","pt":"2","pr":"2","pb":"2","pl":"2","pr_lg":"6","rounded":"rounded"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='2'  pr='2'  pb='2'  pl='2'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='6'  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-2 pe-2 pb-2 ps-2 pe-lg-6 text-center col rounded"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Get in touch","html_tag":"h3","text_color":"primary","font_size":"h4","font_weight":"font-weight-bold","mb_lg":""} -->
<h3 class="wp-block-blockstrap-blockstrap-widget-heading text-primary font-weight-bold h4">Get in touch</h3>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Etiam varius tellus tellus, sit amet rhoncus velit sollicitudin a. Nulla condimentum, orci dapibus commodo laoreet.","html_tag":"div","font_size":"custom","font_size_custom":1,"mb_lg":"","pb_lg":"4"} -->
<div class="wp-block-blockstrap-blockstrap-widget-heading pb-4" style="font-size:1rem">Etiam varius tellus tellus, sit amet rhoncus velit sollicitudin a. Nulla condimentum, orci dapibus commodo laoreet.</div>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:separator {"backgroundColor":"gray","className":"is-style-default"} -->
<hr class="wp-block-separator has-text-color has-gray-color has-alpha-channel-opacity has-gray-background-color has-background is-style-default"/>
<!-- /wp:separator -->

<!-- wp:blockstrap/blockstrap-widget-icon-box {"icon_class":"fa-solid fa-location-dot","title":" ","title_tag":"h2","description":"3131 Rockwell Lane, NC 27834","type":"none","iconbox_size":"medium","icon_color":"primary","icon_text_align_lg":"","title_size":"h5","title_text_align_lg":"","desc_size":"h6","desc_font_weight":"font-weight-light","desc_text_align_lg":"","pt_lg":"4","pb_lg":"4","content":"\u003cdiv class=\u0022blockstrap-iconbox position-relative h-100 pt-4 pb-4 \u0022  \u003e\u003cdiv class=\u0022blockstrap-iconbox-icon text-primary text-center h3  \u0022  \u003e\u003ci class=\u0022fa-solid fa-location-dot   \u0022\u003e\u003c/i\u003e\u003c/div\u003e\u003cdiv class=\u0022iconbox-text-wrap  \u0022\u003e\u003ch2 class=\u0022blockstrap-iconbox-title text-center h5   mb-0\u0022  \u003e \u003c/h2\u003e\u003cdiv class=\u0022blockstrap-iconbox-desc text-center fw-light  h6  \u0022  \u003e3131 Rockwell Lane, NC 27834\u003c/div\u003e\u003c/div\u003e\u003c/div\u003e"} -->
[bs_iconbox icon_class='fa-solid fa-location-dot'  title=' '  title_tag='h2'  description='3131 Rockwell Lane, NC 27834'  type='none'  page_id=''  post_id=''  custom_url=''  icon_position=''  icon_type=''  iconbox_size='medium'  icon_size='h3'  icon_size_custom=''  icon_color='primary'  icon_color_custom=''  icon_bg='primary'  icon_text_align=''  icon_text_align_md=''  icon_text_align_lg=''  icon_pb=''  title_size='h5'  title_size_custom=''  title_font_line_height=''  title_color=''  title_color_custom=''  title_font_weight=''  title_font_case=''  title_text_justify='false'  title_text_align=''  title_text_align_md=''  title_text_align_lg=''  title_pb=''  desc_size='h6'  desc_size_custom=''  desc_font_line_height=''  desc_color=''  desc_color_custom=''  desc_font_weight='font-weight-light'  desc_font_case=''  desc_text_justify='false'  desc_text_align=''  desc_text_align_md=''  desc_text_align_lg=''  desc_pb=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='4'  pr_lg=''  pb_lg='4'  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  hover_animations=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-icon-box -->

<!-- wp:blockstrap/blockstrap-widget-icon-box {"icon_class":"fa-solid fa-phone","title":" ","title_tag":"h2","description":"252-547-3532","type":"none","iconbox_size":"medium","icon_color":"primary","icon_text_align_lg":"","title_size":"h5","title_text_align_lg":"","desc_size":"h6","desc_font_weight":"font-weight-light","desc_text_align_lg":"","pb_lg":"4","content":"\u003cdiv class=\u0022blockstrap-iconbox position-relative h-100 pb-4 \u0022  \u003e\u003cdiv class=\u0022blockstrap-iconbox-icon text-primary text-center h3  \u0022  \u003e\u003ci class=\u0022fa-solid fa-phone   \u0022\u003e\u003c/i\u003e\u003c/div\u003e\u003cdiv class=\u0022iconbox-text-wrap  \u0022\u003e\u003ch2 class=\u0022blockstrap-iconbox-title text-center h5   mb-0\u0022  \u003e \u003c/h2\u003e\u003cdiv class=\u0022blockstrap-iconbox-desc text-center fw-light  h6  \u0022  \u003e252-547-3532\u003c/div\u003e\u003c/div\u003e\u003c/div\u003e"} -->
[bs_iconbox icon_class='fa-solid fa-phone'  title=' '  title_tag='h2'  description='252-547-3532'  type='none'  page_id=''  post_id=''  custom_url=''  icon_position=''  icon_type=''  iconbox_size='medium'  icon_size='h3'  icon_size_custom=''  icon_color='primary'  icon_color_custom=''  icon_bg='primary'  icon_text_align=''  icon_text_align_md=''  icon_text_align_lg=''  icon_pb=''  title_size='h5'  title_size_custom=''  title_font_line_height=''  title_color=''  title_color_custom=''  title_font_weight=''  title_font_case=''  title_text_justify='false'  title_text_align=''  title_text_align_md=''  title_text_align_lg=''  title_pb=''  desc_size='h6'  desc_size_custom=''  desc_font_line_height=''  desc_color=''  desc_color_custom=''  desc_font_weight='font-weight-light'  desc_font_case=''  desc_text_justify='false'  desc_text_align=''  desc_text_align_md=''  desc_text_align_lg=''  desc_pb=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg='4'  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  hover_animations=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-icon-box -->

<!-- wp:blockstrap/blockstrap-widget-icon-box {"icon_class":"fa-solid fa-envelope","title":" ","title_tag":"h2","description":"youremail@example.com","type":"none","iconbox_size":"medium","icon_color":"primary","icon_text_align_lg":"","title_size":"h5","title_text_align_lg":"","desc_size":"h6","desc_font_weight":"font-weight-light","desc_text_align_lg":"","mb_lg":"5","content":"\u003cdiv class=\u0022blockstrap-iconbox position-relative h-100 mb-5 \u0022  \u003e\u003cdiv class=\u0022blockstrap-iconbox-icon text-primary text-center h3  \u0022  \u003e\u003ci class=\u0022fa-solid fa-envelope   \u0022\u003e\u003c/i\u003e\u003c/div\u003e\u003cdiv class=\u0022iconbox-text-wrap  \u0022\u003e\u003ch2 class=\u0022blockstrap-iconbox-title text-center h5   mb-0\u0022  \u003e \u003c/h2\u003e\u003cdiv class=\u0022blockstrap-iconbox-desc text-center fw-light  h6  \u0022  \u003eyouremail@example.com\u003c/div\u003e\u003c/div\u003e\u003c/div\u003e"} -->
[bs_iconbox icon_class='fa-solid fa-envelope'  title=' '  title_tag='h2'  description='youremail@example.com'  type='none'  page_id=''  post_id=''  custom_url=''  icon_position=''  icon_type=''  iconbox_size='medium'  icon_size='h3'  icon_size_custom=''  icon_color='primary'  icon_color_custom=''  icon_bg='primary'  icon_text_align=''  icon_text_align_md=''  icon_text_align_lg=''  icon_pb=''  title_size='h5'  title_size_custom=''  title_font_line_height=''  title_color=''  title_color_custom=''  title_font_weight=''  title_font_case=''  title_text_justify='false'  title_text_align=''  title_text_align_md=''  title_text_align_lg=''  title_pb=''  desc_size='h6'  desc_size_custom=''  desc_font_line_height=''  desc_color=''  desc_color_custom=''  desc_font_weight='font-weight-light'  desc_font_case=''  desc_text_justify='false'  desc_text_align=''  desc_text_align_md=''  desc_text_align_lg=''  desc_pb=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='5'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  hover_animations=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-icon-box -->

<!-- wp:separator {"backgroundColor":"gray","className":"is-style-default"} -->
<hr class="wp-block-separator has-text-color has-gray-color has-alpha-channel-opacity has-gray-background-color has-background is-style-default"/>
<!-- /wp:separator -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Follow us","html_tag":"h4","text_color":"primary","font_size":"h5","mt_lg":"4","mb_lg":"0"} -->
<h4 class="wp-block-blockstrap-blockstrap-widget-heading mt-4 mb-0 text-primary h5">Follow us</h4>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-nav {"inside_navbar":"0","nav_fill":"nav-justified","mr_lg":"","ml_lg":"","width":"w-50"} -->
[bs_nav inside_navbar='0'  container=''  flex_direction=''  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill='nav-justified'  font_size=''  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  width='w-50'  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-nav" id="navbarNav_1"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto nav-justified w-50"><!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#facebook","icon_class":"fab fa-facebook","link_bg":"white","content":"\u003ca href=\u0022##facebook\u0022 class=\u0022nav-link \u0022\u003e\u003ci class=\u0022fab fa-facebook\u0022\u003e\u003c/i\u003e\u003c/a\u003e"} -->
[bs_nav_item type='custom'  page_id=''  post_id=''  custom_url='#facebook'  text=''  icon_class='fab fa-facebook'  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#twriiter","icon_class":"fab fa-twitter","link_bg":"white","content":"\u003ca href=\u0022##twriiter\u0022 class=\u0022nav-link \u0022\u003e\u003ci class=\u0022fab fa-twitter\u0022\u003e\u003c/i\u003e\u003c/a\u003e"} -->
[bs_nav_item type='custom'  page_id=''  post_id=''  custom_url='#twriiter'  text=''  icon_class='fab fa-twitter'  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#instagram","icon_class":"fab fa-instagram","link_bg":"white","content":"\u003ca href=\u0022##instagram\u0022 class=\u0022nav-link \u0022\u003e\u003ci class=\u0022fab fa-instagram\u0022\u003e\u003c/i\u003e\u003c/a\u003e"} -->
[bs_nav_item type='custom'  page_id=''  post_id=''  custom_url='#instagram'  text=''  icon_class='fab fa-instagram'  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item --></ul></div>[/bs_nav]
<!-- /wp:blockstrap/blockstrap-widget-nav --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","row_cols_md":"2","row_cols_lg":"1","mb_lg":"","display_lg":"d-lg-flex","flex_align_items_lg":"align-items-lg-start"} -->
[bs_container container='row'  h100=''  row_cols='1'  row_cols_md='2'  row_cols_lg='1'  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-start'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined row-cols-1 row-cols-md-2 row-cols-lg-1 d-flex row align-items-start"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_lg":"","pt":"2","pr":"2","pb":"2","pl":"2","pr_lg":"0","pl_lg":"0","rounded":"rounded"} -->
[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='2'  pr='2'  pb='2'  pl='2'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='0'  pb_lg=''  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-2 pe-2 pb-2 ps-2 pe-lg-0 ps-lg-0 col rounded"><!-- wp:blockstrap-page-builder-blocks/blockstrap-widget-map {"map_zoom":"16","map_aspect":"21by9","content":"\u003cdiv class=\u0022overflow-hidden mb-3 ratio ratio-21x9\u0022 \u003e\u003ciframe src=\u0022https://maps.google.com/maps?q=Isle of Barra\u0026amp;t=m\u0026amp;z=16\u0026amp;output=embed\u0026amp;iwloc=near\u0022 class=\u0022embed-responsive-item overflow-hidden\u0022 loading=\u0022lazy\u0022 width=\u0022100%\u0022 height=\u0022200\u0022 frameborder=\u00220\u0022 scrolling=\u0022no\u0022 marginheight=\u00220\u0022 marginwidth=\u00220\u0022\u003e\u003c/iframe\u003e\u003c/div\u003e"} -->
[bs_map map_type='upload'  address=''  gps=''  map_zoom='16'  map_view_google=''  map_view_osm='mapnik'  map_aspect='21by9'  col=''  col_md=''  col_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  mask=''  mask_position='center center'  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap-page-builder-blocks/blockstrap-widget-map --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->
