<?php
/**
 * Title: Jobs - Default Header
 * Slug: jobs/header-default
 * Categories: blockstrap-site-header
 * Viewport Width: 1280
 */
?>

<!-- wp:blockstrap/blockstrap-widget-skip-links {"content":"\u003ca href=\u0022#main\u0022 class=\u0022btn btn-primary\u0022\u003eSkip to main content\u003c/a\u003e"} -->
[bs_skip_links text1='Skip to main content'  hash1='main'  text2=''  hash2=''  text3=''  hash3=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-skip-links -->

<!-- wp:blockstrap/blockstrap-widget-navbar {"bg":"white","bg_color":"rgba(255,255,255,0.84)","inner_container":"container","mb_lg":"","pr":"2","pl":"3","pt_lg":"4","pb_lg":"4","border":"0"} -->
[bs_navbar bg='white'  bg_color='rgba(255,255,255,0.84)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bgtus='false'  cscos='false'  container=''  inner_container='container'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='2'  pb=''  pl='3'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='4'  pr_lg=''  pb_lg='4'  pl_lg=''  border='0'  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom='' ]<nav class="navbar navbar-expand-lg pe-2 ps-3 pt-4 pb-4 border-0 bg-white"><div class="wp-block-blockstrap-blockstrap-widget-navbar container"><!-- wp:blockstrap/blockstrap-widget-navbar-brand {"text":"","icon_image":"<?php echo esc_url( get_theme_file_uri( 'assets/images/logo-no-background.png' ) ); ?>","img_max_width":90,"custom_url":"/","brand_font_size":"h1","brand_font_weight":"font-weight-normal","brand_font_italic":"font-italic","bg_gradient":"linear-gradient(135deg,rgb(34,227,7) 0%,rgb(245,245,245) 100%)","bg_on_text":true,"mb_lg":"","rounded_size":"lg"} -->
[bs_navbar_brand text=''  icon_image='<?php echo esc_url( get_theme_file_uri( 'assets/images/logo-no-background.png' ) ); ?>'  img_max_width='90'  type='home'  custom_url='/'  text_color=''  brand_font_size='h1'  brand_font_weight='font-weight-normal'  brand_font_italic='font-italic'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgb(34,227,7) 0%,rgb(245,245,245) 100%)'  bg_on_text='true'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size='lg'  shadow=''  css_class='' ]<a class="navbar-brand d-flex align-items-center rounded-lg" href="http://blockstrap.local"><img class="" alt="Site logo" src="<?php echo esc_url( get_theme_file_uri( 'assets/images/logo-no-background.png' ) ); ?>" style="max-width:90px" width="90" height="50"/><span class="mb-0 props.attributes.brand_font_size props.attributes.brand_font_weight fst-italic"></span></a>[/bs_navbar_brand]
<!-- /wp:blockstrap/blockstrap-widget-navbar-brand -->

<!-- wp:blockstrap/blockstrap-widget-nav {"anchor":"main-nav","inside_navbar":"1","font_size":"fs-base","ml_lg":"","rounded_size":"lg","width":"w-100"} -->
[bs_nav anchor='main-nav'  inside_navbar='1'  container=''  flex_direction=''  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='fs-base'  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='0'  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size='lg'  shadow=''  width='w-100'  css_class='' ]<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav_main-nav" aria-label="Open menu"><span class="navbar-toggler-icon"></span></button><div class="wp-block-blockstrap-blockstrap-widget-nav collapse navbar-collapse" id="navbarNav_main-nav"><ul class="wp-block-blockstrap-blockstrap-widget-nav navbar-nav me-auto ms-auto me-lg-0 rounded-lg w-100 fs-base"><!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"gd_job","page_id":"1858","custom_url":"#about","text":"Jobs","text_color":"dark","ml":"0","ml_lg":"auto","content":"\u003ca href=\u0022#http://blockstrap.local/jobs/\u0022 class=\u0022nav-link link-dark \u0022 \u003eJobs\u003c/a\u003e"} -->
[bs_nav_item type='gd_job'  page_id='1858'  post_id=''  custom_url='#about'  text='Jobs'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml='0'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='auto'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"http://blockstrap.local/category/uncategorized/","text":"Blog","text_color":"dark","content":"\u003ca href=\u0022#http://blockstrap.local/category/uncategorized/\u0022 class=\u0022nav-link link-dark \u0022 \u003eBlog\u003c/a\u003e"} -->
[bs_nav_item type='custom'  page_id=''  post_id=''  custom_url='http://blockstrap.local/category/uncategorized/'  text='Blog'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"1858","custom_url":"#about","text":"Contact","text_color":"dark","mr_lg":"4","content":"\u003ca href=\u0022#http://blockstrap.local/contact/\u0022 class=\u0022nav-link link-dark \u0022 \u003eContact\u003c/a\u003e"} -->
[bs_nav_item type='page'  page_id='1858'  post_id=''  custom_url='#about'  text='Contact'  icon_class=''  icon_aria_label=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='4'  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item -->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"4426","custom_url":"#about","text":"Post a job","link_type":"btn","link_size":"large","link_bg":"primary","font_weight":"font-weight-bold","content":"\u003ca href=\u0022#http://blockstrap.local/add-listing/\u0022 class=\u0022btn btn-primary btn-lg fw-bold \u0022 \u003ePost a job\u003c/a\u003e"} -->
[bs_nav_item type='page'  page_id='4426'  post_id=''  custom_url='#about'  text='Post a job'  icon_class=''  icon_aria_label=''  link_type='btn'  link_size='large'  link_bg='primary'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]
<!-- /wp:blockstrap/blockstrap-widget-nav-item --></ul></div><script>jQuery("#navbarNav_main-nav").on("show.bs.collapse", function () {jQuery("#navbarNav_main-nav").closest(".bg-transparent-until-scroll,.bg-transparent").addClass("nav-menu-open"); jQuery(window).trigger("scroll");});jQuery("#navbarNav_main-nav").on("hidden.bs.collapse", function () {jQuery("#navbarNav_main-nav").closest(".bg-transparent-until-scroll,.bg-transparent").removeClass("nav-menu-open"); jQuery(window).trigger("scroll");});</script>[/bs_nav]
<!-- /wp:blockstrap/blockstrap-widget-nav --></div></nav>[/bs_navbar]
<!-- /wp:blockstrap/blockstrap-widget-navbar -->