<?php
/**
 * Title: Jobs - Hero Home
 * Slug: job-board/hero-home-default
 * Categories: blockstrap-hero-sections
 * Viewport Width: 1280
 */

$img_url = esc_url( get_theme_file_uri( 'assets/images/demo/thinking.svg' ) ); /* <?php echo esc_url( $img_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-light-blue","bg_color":"#fef7f9","bg_gradient":"linear-gradient(90deg,rgba(0,0,0,0.73) 4%,rgba(121,33,12,0.86) 100%)","bg_image_xy":{"x":0.75,"y":0.99},"text_color":"white","mb_lg":"","pt":"6","pb":"0","pt_lg":"10","pb_lg":"9","position":"position-relative","content":""} -->
[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-light-blue'  bg_color='#fef7f9'  bg_gradient='linear-gradient(90deg,rgba(0,0,0,0.73) 4%,rgba(121,33,12,0.86) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:0.75,y:0.99}'  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='6'  pr=''  pb='0'  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='10'  pr_lg=''  pb_lg='9'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-6 pb-0 pt-lg-10 pb-lg-9 bg-custom-light-blue text-white container-fluid position-relative"><!-- wp:blockstrap/blockstrap-widget-container {"mb_lg":"","pl_lg":"4"} -->
    [bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='4'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined ps-4 container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","mb_lg":"","flex_align_items_lg":"align-items-lg-center"} -->
        [bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined row align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_lg":"6","mb_lg":"","pt_lg":"0","pr_lg":"5","pb_lg":"0","pl_lg":"0"} -->
            [bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md=''  col_lg='6'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg='5'  pb_lg='0'  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-0 pe-5 pb-0 ps-0 col-12 col-lg-6 col"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"The perfect job is just a click away.","html_tag":"h1","text_color":"custom-dark-black","text_color_custom":"#0c0d24","font_size":"display-3","font_weight":"font-weight-bold"} -->
                <h1 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-custom-dark-black font-weight-bold display-3">The perfect job is just a click away.</h1>
                <!-- /wp:blockstrap/blockstrap-widget-heading -->

                <!-- wp:blockstrap/blockstrap-widget-heading {"text":"Let us help you find your next big opportunity.","html_tag":"p","text_color":"dark","mt":"3","mb":"4","mr_md":"0","ml_md":"0","mt_lg":"3","mr_lg":"7","mb_lg":"4"} -->
                <p class="wp-block-blockstrap-blockstrap-widget-heading mt-3 mb-4 me-md-0 ms-md-0 mt-lg-3 me-7 mb-lg-4 text-dark">Let us help you find your next big opportunity.</p>
                <!-- /wp:blockstrap/blockstrap-widget-heading -->

                <!-- wp:geodirectory/geodir-widget-search {"post_type":"gd_job","post_type_hide":true,"input_size":"lg","input_border":"0","btn_bg":"primary","btn_rounded_size_lg":"1","bg":"white","mt":"5","pt":"3","pr":"3","pb":"3","pl":"2","border":"0","rounded":"rounded","shadow":"shadow","content":""} -->
                <div class="wp-block-geodirectory-geodir-widget-search">[gd_search post_type='gd_job'  post_type_hide='true'  hide_search_input='false'  hide_near_input='false'  input_size='lg'  bar_flex_wrap=''  bar_flex_wrap_md=''  bar_flex_wrap_lg=''  input_border='0'  input_border_opacity=''  input_rounded_size=''  btn_bg='primary'  btn_rounded_size=''  btn_rounded_size_md=''  btn_rounded_size_lg='1'  bg='white'  mt='5'  mr=''  mb='3'  ml=''  pt='3'  pr='3'  pb='3'  pl='2'  border='0'  rounded='rounded'  rounded_size=''  rounded_size_md=''  rounded_size_lg=''  shadow='shadow'  css_class='' ]</div>
                <!-- /wp:geodirectory/geodir-widget-search --></div>[/bs_container]
            <!-- /wp:blockstrap/blockstrap-widget-container -->

            <!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_lg":"6","mb_lg":"","pt":"4","pt_lg":"0","pr_lg":"0","pb_lg":"0","pl_lg":"6"} -->
            [bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md=''  col_lg='6'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='4'  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg='0'  pb_lg='0'  pl_lg='6'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-4 pt-lg-0 pe-0 pb-0 ps-6 col-12 col-lg-6 col"><!-- wp:blockstrap/blockstrap-widget-image {"img_src":"url","img_url":"<?php echo esc_url( $img_url ); ?>","fallback_img_src":"default","img_alt":"Man laptop","img_cover":"n","img_rounded":"rounded","mb_lg":"","content":""} -->
                [bs_image img_src='url'  img_image=''  img_image_id=''  img_size=''  img_url='<?php echo esc_url( $img_url ); ?>'  fallback_img_src='default'  fallback_img_image=''  fallback_img_image_id=''  img_alt='Man laptop'  img_lazyload=''  img_link_to=''  img_link=''  img_link_lightbox=''  lightbox_size='full'  img_link_hover_effect=''  text=''  col=''  col_md=''  col_lg=''  img_aspect=''  img_cover='n'  img_border=''  img_rounded='rounded'  img_rounded_size=''  img_shadow=''  img_overlay=''  text_color=''  font_size=''  font_size_custom=''  font_weight=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  float=''  float_md=''  float_lg=''  img_mask=''  img_mask_position='center center'  visibility_conditions=''  css_class='' ]
                <!-- /wp:blockstrap/blockstrap-widget-image --></div>[/bs_container]
            <!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
        <!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
    <!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->