<?php
/**
 * Title: Jobs: 3-column cards (Latest articles)
 * Slug: job-board/three-col-posts
 * Categories: blockstrap-page-content
 * Viewport Width: 1280
 */
?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg_color":"rgba(255,248,247,0.65)","mb_lg":"","pt_lg":"7","pb_lg":"6","position":"position-relative"} -->
[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='rgba(255,248,247,0.65)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='7'  pr_lg=''  pb_lg='6'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-7 pb-6 container-fluid position-relative"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","text_align_lg":"text-lg-center","mb_lg":"","pb":"0","pb_lg":"4","flex_align_items_lg":"align-items-lg-center"} -->
    [bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb='0'  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg='4'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pb-0 pb-lg-4 text-center row align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_lg":""} -->
        [bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined col"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Latest articles \u0026amp; news","html_tag":"h2","font_size":"h1","font_weight":"font-weight-bold","mb_lg":"2"} -->
            <h2 class="wp-block-blockstrap-blockstrap-widget-heading mb-2 font-weight-bold h1">Latest articles &amp; news</h2>
            <!-- /wp:blockstrap/blockstrap-widget-heading -->

            <!-- wp:blockstrap/blockstrap-widget-heading {"text":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore","html_tag":"div","font_size":"h6","font_weight":"font-weight-normal","mb_lg":"","pr":"0","pl":"0","pr_lg":"11","pl_lg":"11"} -->
            <div class="wp-block-blockstrap-blockstrap-widget-heading pe-0 ps-0 pe-lg-11 ps-lg-11 font-weight-normal h6">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</div>
            <!-- /wp:blockstrap/blockstrap-widget-heading --></div>[/bs_container]
        <!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
    <!-- /wp:blockstrap/blockstrap-widget-container -->

    <!-- wp:blockstrap/blockstrap-widget-container {"bg_color":"rgba(0,0,0,0.03)","mb_lg":"","anchor":"main","css_class":"align-items-center"} -->
    [bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='rgba(0,0,0,0.03)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor='main'  css_class='align-items-center' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined container align-items-center" id="main"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","row_cols_md":"2","row_cols_lg":"1","mb_lg":""} -->
        [bs_container container='row'  h100=''  row_cols='1'  row_cols_md='2'  row_cols_lg='1'  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined row-cols-1 row-cols-md-2 row-cols-lg-1 row"><!-- wp:query {"queryId":1,"query":{"pages":"","offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","sticky":"","exclude":[],"perPage":"3","inherit":false},"layout":{"type":"default"}} -->
            <div class="wp-block-query"><!-- wp:post-template {"layout":{"type":"grid","columnCount":3}} -->
                <!-- wp:blockstrap/blockstrap-widget-container {"container":"card","h100":"h-100","bg":"white","mt_lg":"3","mb_lg":"","pt_lg":"0","pr_lg":"0","pb_lg":"0","pl_lg":"0","border":"0","rounded":"rounded","rounded_size":"lg","shadow":"shadow-sm","overflow":"overflow-hidden"} -->
                [bs_container container='card'  h100='h-100'  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='white'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='3'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg='0'  pb_lg='0'  pl_lg='0'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size='lg'  shadow='shadow-sm'  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow='overflow-hidden'  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mt-3 pt-0 pe-0 pb-0 ps-0 border-0 rounded-lg bg-white card shadow-sm rounded h-100 overflow-hidden"><!-- wp:blockstrap/blockstrap-widget-container {"container":"card-img-top","bg":"white","mb_lg":"","border":"0","border_type":"border","rounded_size":"0","overflow":"overflow-hidden"} -->
                    [bs_container container='card-img-top'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='white'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  border_type='border'  border_width=''  border_opacity=''  rounded=''  rounded_size='0'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow='overflow-hidden'  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined border-0 rounded-0 bg-white card-img-top border overflow-hidden"><!-- wp:blockstrap/blockstrap-widget-image {"img_src":"featured","fallback_img_src":"default","img_link_to":"post","img_aspect":"1by1","img_border":"0","img_rounded_size":"0","mb_lg":"0","border":"0","rounded_size":"0","content":""} -->
                        [bs_image img_src='featured'  img_image=''  img_image_id=''  img_size=''  img_url=''  fallback_img_src='default'  fallback_img_image=''  fallback_img_image_id=''  img_alt=''  img_lazyload=''  img_link_to='post'  img_link=''  img_link_lightbox=''  lightbox_size='full'  img_link_hover_effect=''  text=''  col=''  col_md=''  col_lg=''  img_aspect='1by1'  img_cover=''  img_border='0'  img_rounded=''  img_rounded_size='0'  img_shadow=''  img_overlay=''  text_color=''  font_size=''  font_size_custom=''  font_weight=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='0'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  rounded=''  rounded_size='0'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  float=''  float_md=''  float_lg=''  img_mask=''  img_mask_position='center center'  visibility_conditions=''  css_class='' ]
                        <!-- /wp:blockstrap/blockstrap-widget-image --></div>[/bs_container]
                    <!-- /wp:blockstrap/blockstrap-widget-container -->

                    <!-- wp:blockstrap/blockstrap-widget-container {"container":"card-body","mb_lg":"","pt_lg":"4","pr_lg":"4","pb_lg":"4","pl_lg":"4","rounded":"rounded"} -->
                    [bs_container container='card-body'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='4'  pr_lg='4'  pb_lg='4'  pl_lg='4'  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined pt-4 pe-4 pb-4 ps-4 card-body rounded"><!-- wp:post-date {"style":{"typography":{"fontSize":"0.9rem","fontStyle":"normal","fontWeight":"600"}},"textColor":"secondary"} /-->

                        <!-- wp:spacer {"height":"7px"} -->
                        <div style="height:7px" aria-hidden="true" class="wp-block-spacer"></div>
                        <!-- /wp:spacer -->

                        <!-- wp:post-title {"isLink":true,"style":{"elements":{"link":{"color":{"text":"var:preset|color|dark"}}},"typography":{"fontStyle":"normal","fontWeight":"700"}},"textColor":"dark","fontSize":"medium"} /-->

                        <!-- wp:separator {"backgroundColor":"light","className":"is-style-wide"} -->
                        <hr class="wp-block-separator has-text-color has-light-color has-alpha-channel-opacity has-light-background-color has-background is-style-wide"/>
                        <!-- /wp:separator -->

                        <!-- wp:spacer {"height":"13px"} -->
                        <div style="height:13px" aria-hidden="true" class="wp-block-spacer"></div>
                        <!-- /wp:spacer -->

                        <!-- wp:post-terms {"term":"category","textAlign":"left","style":{"typography":{"fontSize":"0.9rem","fontStyle":"normal","fontWeight":"600"}},"textColor":"secondary"} /-->

                        <!-- wp:post-terms {"term":"post_tag","style":{"spacing":{"padding":{"top":"2em"}}}} /--></div>[/bs_container]
                    <!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
                <!-- /wp:blockstrap/blockstrap-widget-container -->
                <!-- /wp:post-template --></div>
            <!-- /wp:query --></div>[/bs_container]
        <!-- /wp:blockstrap/blockstrap-widget-container -->

        <!-- wp:blockstrap/blockstrap-widget-container {"container":"row","text_align_lg":"text-lg-center","mt_lg":"2","mb_lg":""} -->
        [bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='2'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined mt-2 text-center row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_lg":""} -->
            [bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_image_xy='{x:undefined,y:undefined}'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]<div class="wp-block-blockstrap-blockstrap-widget-container undefined col"><!-- wp:blockstrap/blockstrap-widget-button {"type":"custom","custom_url":"#","text":"See all","link_size":"large","bg_hover":"secondary","font_weight":"font-weight-bold","mt_lg":"2","pt_lg":"3","pb_lg":"3","styleid":"block-uceu972akzk","content":""} -->
                [bs_button type='custom'  page_id=''  meta_key=''  post_id=''  custom_url='#'  text='See all'  icon_class=''  icon_position=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type='btn'  link_size='large'  link_bg='primary'  link_bg_color='#0073aa'  link_bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color=''  text_color_custom=''  bg_hover='secondary'  bg_hover_color='#0073aa'  bg_hover_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color_hover=''  text_color_hover_custom=''  font_size_custom=''  font_weight='font-weight-bold'  font_case=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='2'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg=''  pb_lg='3'  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  display=''  display_md=''  display_lg=''  visibility_conditions=''  css_class=''  styleid='block-uceu972akzk' ]
                <!-- /wp:blockstrap/blockstrap-widget-button --></div>[/bs_container]
            <!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
        <!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
    <!-- /wp:blockstrap/blockstrap-widget-container --></div>[/bs_container]
<!-- /wp:blockstrap/blockstrap-widget-container -->